name: Lab3 Test

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  test:
    name: Run Go Test
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.15'

    - name: Check out code
      uses: actions/checkout@v2

    - name: Run tests 3A
      run: go test -run 3A -race
      working-directory: ./src/kvraft

    # - name: Run tests 3B
    #   run: go test -run 3B
    #   working-directory: ./src/kvraft



