name: Lab 2 Raft

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  test:
    name: Run Go Test
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.15'

    - name: Check out code
      uses: actions/checkout@v2

    - name: Run tests 2A
      run: go test -run 2A
      working-directory: ./src/raft

    - name: Run tests 2B
      run: go test -run 2B
      working-directory: ./src/raft

    - name: Run tests 2C
      run: go test -run 2C
      working-directory: ./src/raft

    - name: Run tests 2D
      run: go test -run 2D
      working-directory: ./src/raft

    - name: Run tests 2 Race
      run: go test -run 2 -race
      working-directory: ./src/raft



