name: Lab1 Test

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  test:
    name: Run Go Test
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.15'

    - name: Check out code
      uses: actions/checkout@v2

    - name: Run test-mr-many.sh
      run: bash ./test-mr-many.sh 3
      working-directory: ./src/main



